[tool.poetry]
name = "django-flex-reviews"
version = "0.1.0"
description = ""
authors = ["Niicck <niicck@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "django_flex_reviews"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
